@startuml
actor user
participant AccountsGUI
participant AccountActions
participant JournalDataModel
participant JournalInputGUI
participant Main

user-->>AccountsGUI:debet/credit
AccountsGUI->>AccountsGUI:book(boolean debit)
AccountsGUI->>AccountActions:addBookingToTransaction
AccountActions-->>user:askAmount
user-->>AccountActions
note right:booking =\nnew Booking()
AccountActions->>AccountsGUI:booking
note left:transaction.\naddBooking\n(booking)
AccountsGUI->>Main:fireTransactionDataChanged
group Main.fireTransactionDataChanged()
Main-->>JournalInputGUI
group JournalInputGUI.fireTransactionDataChanged()
JournalInputGUI->>JournalDataModel:fireTableDataChanged
JournalInputGUI->>JournalInputGUI:activate buttons\n and fields
end
end
JournalInputGUI-->>user:the new booking is now visible for the user
@enduml
